numbers: main.o sum.o sum_squares.o sum_primes.o
	gcc main.o sum.o sum_squares.o sum_primes.o -o numbers

sum.o: sum.c
	gcc -c sum.c

sum_squares.o: sum_squares.c
	gcc -c sum_squares.c

sum_primes.o: sum_primes.c
	gcc -c sum_primes.c

main.o: main.c
	gcc -c main.c
